name: smooth-loader-docs

services:
    app:
        image: smooth-loader-docs
        container_name: smooth-loader-docs
        build:
            context: .
            dockerfile: Containerfile
        volumes:
            - .:/app:z
            - /app/node_modules
        ports:
            - 3000:5173
